on:
  push:
    branches: [master,update/coastat_save_jpgs]
  pull_request:
    branches: [master]

name: Test on Multiple OS with Python 3.9
jobs:
  Test:
    name: ${{ matrix.os }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        env:
          - ci/envs/39-coastsat.yml
          - ci/envs/38-coastsat.yml
        include:
          - env: ci/envs/39-coastsat.yml
            os: macos-latest
          - env: ci/envs/39-coastsat.yml
            os: windows-latest
          - env: ci/envs/39-coastsat.yml
            os: ubuntu-latest
          - env: ci/envs/38-coastsat.yml
            os: macos-latest
          - env: ci/envs/38-coastsat.yml
            os: windows-latest
          - env: ci/envs/38-coastsat.yml
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Conda with python 3.9
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ${{ matrix.env }}
          miniconda-version: "latest"
      - run: |
          conda info
          conda list
      - name: Install Latest coastsat-package
        run: |
          python -m pip install --upgrade pip
          pip install coastsat-package -U